---
abstract: 'Base class for HTML formatters'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
  - 'Sean M Burke <sburke@cpan.org>'
  - 'Gisle Aas <gisle@ActiveState.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Slurper: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.96'
  Test::Warnings: '0'
  blib: '1.01'
  bytes: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Formatter
provides:
  HTML::FormatMarkdown:
    file: lib/HTML/FormatMarkdown.pm
    version: '2.16'
  HTML::FormatPS:
    file: lib/HTML/FormatPS.pm
    version: '2.16'
  HTML::FormatRTF:
    file: lib/HTML/FormatRTF.pm
    version: '2.16'
  HTML::FormatText:
    file: lib/HTML/FormatText.pm
    version: '2.16'
  HTML::Formatter:
    file: lib/HTML/Formatter.pm
    version: '2.16'
requires:
  Carp: '0'
  Data::Dumper: '0'
  Encode: '0'
  Font::Metrics::Courier: '0'
  Font::Metrics::CourierBold: '0'
  Font::Metrics::CourierBoldOblique: '0'
  Font::Metrics::CourierOblique: '0'
  Font::Metrics::Helvetica: '0'
  Font::Metrics::HelveticaBold: '0'
  Font::Metrics::HelveticaBoldOblique: '0'
  Font::Metrics::HelveticaOblique: '0'
  Font::Metrics::TimesBold: '0'
  Font::Metrics::TimesBoldItalic: '0'
  Font::Metrics::TimesItalic: '0'
  Font::Metrics::TimesRoman: '0'
  HTML::Element: '3.15'
  HTML::TreeBuilder: '0'
  IO::File: '0'
  base: '0'
  integer: '0'
  parent: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=HTML-Formatter
  homepage: https://metacpan.org/release/HTML-Formatter
  repository: https://github.com/nigelm/html-formatter.git
version: '2.16'
x_Dist_Zilla:
  perl:
    version: '5.024000'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.01'
          version_by_branch: 0
          version_regexp: (?^:^release/(\d+(?:\.\d+)+)(?:[-_].+)?$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::NextVersion'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README
            - README.pod
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::Check'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::CheckFor::CorrectBranch'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::CheckFor::MergeConflicts'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory:
            - local
            - vendor
          root: .
      name: '@NIGELM/GatherDir'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: test
          script_finder:
            - ':PerlExecFiles'
          skips: []
      name: '@NIGELM/Test::Compile'
      version: '2.054'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@NIGELM/Test::Perl::Critic'
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@NIGELM/MetaTests'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@NIGELM/PodSyntaxTests'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      config:
        Dist::Zilla::Plugin::Test::PodSpelling:
          directories:
            - bin
            - lib
          spell_cmd: ''
          stopwords: []
          wordlist: Pod::Wordlist
      name: '@NIGELM/Test::PodSpelling'
      version: '2.007003'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      config:
        Dist::Zilla::Plugin::Test::Portability:
          options: ''
      name: '@NIGELM/Test::Portability'
      version: '2.001000'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@NIGELM/Test::Synopsis'
      version: '2.000007'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@NIGELM/Test::MinimumVersion'
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@NIGELM/HasVersionTests'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@NIGELM/Test::DistManifest'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@NIGELM/Test::UnusedVars'
      version: '2.000007'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':ExecFiles'
            - ':InstallModules'
            - ':TestFiles'
          trailing_whitespace: 0
      name: '@NIGELM/Test::EOL'
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@NIGELM/Test::ReportPrereqs'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::InlineFiles
      name: '@NIGELM/InlineFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@NIGELM/PruneCruft'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@NIGELM/PruneFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@NIGELM/ManifestSkip'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@NIGELM/AutoPrereqs'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@NIGELM/MetaConfig'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Class
      config:
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002003'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@NIGELM/MetaProvides::Class'
      version: '2.001000'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@NIGELM/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.007'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002003'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@NIGELM/MetaProvides::Package'
      version: '2.004002'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@NIGELM/MetaResources'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@NIGELM/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@NIGELM/ExtraTests'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@NIGELM/NextRelease'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@NIGELM/OurPkgVersion'
      version: '0.10'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@DAGOLDEN'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@DAGOLDEN/SingleEncoding'
              version: '4.014'
            -
              class: Pod::Weaver::Plugin::WikiDoc
              name: '@DAGOLDEN/WikiDoc'
              version: '0.093004'
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.014'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Name
              name: '@DAGOLDEN/Name'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Version
              name: '@DAGOLDEN/Version'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Region
              name: '@DAGOLDEN/Prelude'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: '@DAGOLDEN/Synopsis'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: '@DAGOLDEN/Description'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: '@DAGOLDEN/Usage'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: '@DAGOLDEN/Overview'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Generic
              name: '@DAGOLDEN/Stability'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: Requirements
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: Constructors
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: '4.014'
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: '4.014'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@DAGOLDEN/Leftovers'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Region
              name: '@DAGOLDEN/postlude'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Support
              name: '@DAGOLDEN/Support'
              version: '1.007'
            -
              class: Pod::Weaver::Section::Authors
              name: '@DAGOLDEN/Authors'
              version: '4.014'
            -
              class: Pod::Weaver::Section::Contributors
              name: '@DAGOLDEN/Contributors'
              version: '0.009'
            -
              class: Pod::Weaver::Section::Legal
              name: '@DAGOLDEN/Legal'
              version: '4.014'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@DAGOLDEN/List'
              version: '4.014'
      name: '@NIGELM/PodWeaver'
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::License
      name: '@NIGELM/License'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@NIGELM/MakeMaker'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@NIGELM/MetaYAML'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@NIGELM/MetaJSON'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@NIGELM/ReadmeTextInBuild'
      version: '0.161170'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@NIGELM/ReadmePodInRoot'
      version: '0.161170'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@NIGELM/InstallGuide'
      version: '1.200007'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@NIGELM/Manifest'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - README
            - README.pod
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@NIGELM/Git::Commit'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: release/2.16
          tag_format: release/%v%t
          tag_message: 'Release of %v%t'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@NIGELM/Git::Tag'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: ''
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: cpan
          release_message: 'CPAN Release of %v%t'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::CommitBuild'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@NIGELM/Git::Push'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@NIGELM/CheckChangeLog'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@NIGELM/UploadToCPAN'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: Test::NoTabs
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@NIGELM/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.007'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.007'
x_authority: cpan:NIGELM
x_serialization_backend: 'YAML::Tiny version 1.69'
